import type { Metadata } from 'next';
import NavBar from '../components/NavBar/NavBar';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Wikied',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
